/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * CreditWithFriends API
 * Versioned API for CreditWithFriends.
 * OpenAPI spec version: 1.0.0
 */
import { apiFetch } from './fetcher';
export interface SignOutDataDto {
  signedOut: boolean;
}

/**
 * @nullable
 */
export type SignOutResponseDtoError =
  (typeof SignOutResponseDtoError)[keyof typeof SignOutResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignOutResponseDtoError = {} as const;

export interface SignOutResponseDto {
  success: boolean;
  data: SignOutDataDto;
  /** @nullable */
  error: SignOutResponseDtoError;
}

export interface ApiFieldErrorDto {
  /** Name of the invalid field. */
  field: string;
  /** Stable validation reason. */
  reason: string;
}

export interface ApiErrorDetailsDto {
  fieldErrors?: ApiFieldErrorDto[];
}

export interface ApiErrorDto {
  errorId: string;
  code: string;
  type: string;
  message: string;
  userMessage: string;
  details: ApiErrorDetailsDto;
  statusCode: number;
  correlationId: string;
  /** @nullable */
  requestId: string | null;
  environment: string;
  timestampUtc: string;
}

/**
 * @nullable
 */
export type ApiErrorResponseDtoData =
  (typeof ApiErrorResponseDtoData)[keyof typeof ApiErrorResponseDtoData] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiErrorResponseDtoData = {} as const;

export interface ApiErrorResponseDto {
  success: boolean;
  /** @nullable */
  data: ApiErrorResponseDtoData;
  error: ApiErrorDto;
}

export interface PendingDataDto {
  name: string;
  email: string;
  returnPath: string;
}

/**
 * @nullable
 */
export type PendingResponseDtoError =
  (typeof PendingResponseDtoError)[keyof typeof PendingResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PendingResponseDtoError = {} as const;

export interface PendingResponseDto {
  success: boolean;
  data: PendingDataDto;
  /** @nullable */
  error: PendingResponseDtoError;
}

export interface NoticeDataDto {
  version: number;
  text: string;
}

/**
 * @nullable
 */
export type NoticeResponseDtoError =
  (typeof NoticeResponseDtoError)[keyof typeof NoticeResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoticeResponseDtoError = {} as const;

export interface NoticeResponseDto {
  success: boolean;
  data: NoticeDataDto;
  /** @nullable */
  error: NoticeResponseDtoError;
}

export interface OnboardingDto {
  displayName: string;
  whatsappNumber: string;
  isAdultConfirmed: boolean;
  isConsentGiven: boolean;
  privacyNoticeVersion: number;
}

export interface MemberDataDto {
  id: string;
  displayName: string;
  whatsappE164: string;
  googleEmail: string;
  googleAccountId: string;
}

/**
 * @nullable
 */
export type MemberResponseDtoError =
  (typeof MemberResponseDtoError)[keyof typeof MemberResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberResponseDtoError = {} as const;

export interface MemberResponseDto {
  success: boolean;
  data: MemberDataDto;
  /** @nullable */
  error: MemberResponseDtoError;
}

export interface ActionDataDto {
  removed: boolean;
}

/**
 * @nullable
 */
export type ActionResponseDtoError =
  (typeof ActionResponseDtoError)[keyof typeof ActionResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionResponseDtoError = {} as const;

export interface ActionResponseDto {
  success: boolean;
  data: ActionDataDto;
  /** @nullable */
  error: ActionResponseDtoError;
}

export interface HealthDataDto {
  /** Indicates that the API process is ready. */
  status: string;
}

/**
 * @nullable
 */
export type HealthResponseDtoError =
  (typeof HealthResponseDtoError)[keyof typeof HealthResponseDtoError] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseDtoError = {} as const;

export interface HealthResponseDto {
  success: boolean;
  data: HealthDataDto;
  /** @nullable */
  error: HealthResponseDtoError;
}

export type GoogleControllerStartParams = {
  returnTo?: string;
};

/**
 * @summary Sign out of this device
 */
export type sessionsControllerSignOutResponse201 = {
  data: SignOutResponseDto;
  status: 201;
};

export type sessionsControllerSignOutResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type sessionsControllerSignOutResponseSuccess =
  sessionsControllerSignOutResponse201 & {
    headers: Headers;
  };
export type sessionsControllerSignOutResponseError =
  sessionsControllerSignOutResponse401 & {
    headers: Headers;
  };

export type sessionsControllerSignOutResponse =
  | sessionsControllerSignOutResponseSuccess
  | sessionsControllerSignOutResponseError;

export const getSessionsControllerSignOutUrl = () => {
  return `/api/v1/sessions/sign-out`;
};

export const sessionsControllerSignOut = async (
  options?: RequestInit,
): Promise<sessionsControllerSignOutResponse> => {
  return apiFetch<sessionsControllerSignOutResponse>(
    getSessionsControllerSignOutUrl(),
    {
      ...options,
      method: 'POST',
    },
  );
};

/**
 * @summary Get pending sign-in information
 */
export type accountsControllerPendingResponse200 = {
  data: PendingResponseDto;
  status: 200;
};

export type accountsControllerPendingResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type accountsControllerPendingResponseSuccess =
  accountsControllerPendingResponse200 & {
    headers: Headers;
  };
export type accountsControllerPendingResponseError =
  accountsControllerPendingResponse401 & {
    headers: Headers;
  };

export type accountsControllerPendingResponse =
  | accountsControllerPendingResponseSuccess
  | accountsControllerPendingResponseError;

export const getAccountsControllerPendingUrl = () => {
  return `/api/v1/sign-ins`;
};

export const accountsControllerPending = async (
  options?: RequestInit,
): Promise<accountsControllerPendingResponse> => {
  return apiFetch<accountsControllerPendingResponse>(
    getAccountsControllerPendingUrl(),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * @summary Read the current privacy notice
 */
export type accountsControllerNoticeResponse200 = {
  data: NoticeResponseDto;
  status: 200;
};

export type accountsControllerNoticeResponse403 = {
  data: ApiErrorResponseDto;
  status: 403;
};

export type accountsControllerNoticeResponseSuccess =
  accountsControllerNoticeResponse200 & {
    headers: Headers;
  };
export type accountsControllerNoticeResponseError =
  accountsControllerNoticeResponse403 & {
    headers: Headers;
  };

export type accountsControllerNoticeResponse =
  | accountsControllerNoticeResponseSuccess
  | accountsControllerNoticeResponseError;

export const getAccountsControllerNoticeUrl = () => {
  return `/api/v1/privacy-notice`;
};

export const accountsControllerNotice = async (
  options?: RequestInit,
): Promise<accountsControllerNoticeResponse> => {
  return apiFetch<accountsControllerNoticeResponse>(
    getAccountsControllerNoticeUrl(),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * @summary Complete onboarding and join
 */
export type accountsControllerOnboardResponse200 = {
  data: MemberResponseDto;
  status: 200;
};

export type accountsControllerOnboardResponse400 = {
  data: ApiErrorResponseDto;
  status: 400;
};

export type accountsControllerOnboardResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type accountsControllerOnboardResponseSuccess =
  accountsControllerOnboardResponse200 & {
    headers: Headers;
  };
export type accountsControllerOnboardResponseError = (
  accountsControllerOnboardResponse400 | accountsControllerOnboardResponse401
) & {
  headers: Headers;
};

export type accountsControllerOnboardResponse =
  | accountsControllerOnboardResponseSuccess
  | accountsControllerOnboardResponseError;

export const getAccountsControllerOnboardUrl = () => {
  return `/api/v1/onboarding`;
};

export const accountsControllerOnboard = async (
  onboardingDto: OnboardingDto,
  options?: RequestInit,
): Promise<accountsControllerOnboardResponse> => {
  return apiFetch<accountsControllerOnboardResponse>(
    getAccountsControllerOnboardUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(onboardingDto),
    },
  );
};

/**
 * @summary Cancel and remove pending sign-in
 */
export type accountsControllerCancelResponse200 = {
  data: ActionResponseDto;
  status: 200;
};

export type accountsControllerCancelResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type accountsControllerCancelResponseSuccess =
  accountsControllerCancelResponse200 & {
    headers: Headers;
  };
export type accountsControllerCancelResponseError =
  accountsControllerCancelResponse401 & {
    headers: Headers;
  };

export type accountsControllerCancelResponse =
  | accountsControllerCancelResponseSuccess
  | accountsControllerCancelResponseError;

export const getAccountsControllerCancelUrl = () => {
  return `/api/v1/sign-ins/cancel`;
};

export const accountsControllerCancel = async (
  options?: RequestInit,
): Promise<accountsControllerCancelResponse> => {
  return apiFetch<accountsControllerCancelResponse>(
    getAccountsControllerCancelUrl(),
    {
      ...options,
      method: 'POST',
    },
  );
};

/**
 * @summary Read your own member account
 */
export type accountsControllerMeResponse200 = {
  data: MemberResponseDto;
  status: 200;
};

export type accountsControllerMeResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type accountsControllerMeResponse403 = {
  data: ApiErrorResponseDto;
  status: 403;
};

export type accountsControllerMeResponseSuccess =
  accountsControllerMeResponse200 & {
    headers: Headers;
  };
export type accountsControllerMeResponseError = (
  accountsControllerMeResponse401 | accountsControllerMeResponse403
) & {
  headers: Headers;
};

export type accountsControllerMeResponse =
  accountsControllerMeResponseSuccess | accountsControllerMeResponseError;

export const getAccountsControllerMeUrl = () => {
  return `/api/v1/members/me`;
};

export const accountsControllerMe = async (
  options?: RequestInit,
): Promise<accountsControllerMeResponse> => {
  return apiFetch<accountsControllerMeResponse>(getAccountsControllerMeUrl(), {
    ...options,
    method: 'GET',
  });
};

/**
 * @summary Start Google sign-in
 */
export type googleControllerStartResponse302 = {
  data: void;
  status: 302;
};

export type googleControllerStartResponseError =
  googleControllerStartResponse302 & {
    headers: Headers;
  };

export type googleControllerStartResponse = googleControllerStartResponseError;

export const getGoogleControllerStartUrl = (
  params?: GoogleControllerStartParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/auth/google/start?${stringifiedParams}`
    : `/api/v1/auth/google/start`;
};

export const googleControllerStart = async (
  params?: GoogleControllerStartParams,
  options?: RequestInit,
): Promise<googleControllerStartResponse> => {
  return apiFetch<googleControllerStartResponse>(
    getGoogleControllerStartUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * @summary Complete Google sign-in
 */
export type googleControllerCallbackResponse302 = {
  data: void;
  status: 302;
};

export type googleControllerCallbackResponse401 = {
  data: ApiErrorResponseDto;
  status: 401;
};

export type googleControllerCallbackResponseError = (
  googleControllerCallbackResponse302 | googleControllerCallbackResponse401
) & {
  headers: Headers;
};

export type googleControllerCallbackResponse =
  googleControllerCallbackResponseError;

export const getGoogleControllerCallbackUrl = () => {
  return `/api/v1/auth/google/callback`;
};

export const googleControllerCallback = async (
  options?: RequestInit,
): Promise<googleControllerCallbackResponse> => {
  return apiFetch<googleControllerCallbackResponse>(
    getGoogleControllerCallbackUrl(),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * Returns the readiness of the API process.
 * @summary Check API health
 */
export type healthControllerGetHealthResponse200 = {
  data: HealthResponseDto;
  status: 200;
};

export type healthControllerGetHealthResponse429 = {
  data: ApiErrorResponseDto;
  status: 429;
};

export type healthControllerGetHealthResponse500 = {
  data: ApiErrorResponseDto;
  status: 500;
};

export type healthControllerGetHealthResponseSuccess =
  healthControllerGetHealthResponse200 & {
    headers: Headers;
  };
export type healthControllerGetHealthResponseError = (
  healthControllerGetHealthResponse429 | healthControllerGetHealthResponse500
) & {
  headers: Headers;
};

export type healthControllerGetHealthResponse =
  | healthControllerGetHealthResponseSuccess
  | healthControllerGetHealthResponseError;

export const getHealthControllerGetHealthUrl = () => {
  return `/api/v1/health`;
};

export const healthControllerGetHealth = async (
  options?: RequestInit,
): Promise<healthControllerGetHealthResponse> => {
  return apiFetch<healthControllerGetHealthResponse>(
    getHealthControllerGetHealthUrl(),
    {
      ...options,
      method: 'GET',
    },
  );
};
